name: crimetracker
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - geopandas
  - pandas
  - ipykernel
  - dash
  - dash-bootstrap-components
  - nbformat
  - plotly
  - pyarrow
  - pip
  - pip:
      - dash-vega-components
